### ISSUE TITLE
The links after chapter 3 don't work

### ISSUE THREAD

**Issue by GEJXD** [xinychen/latex-cookbook#8]
as the tittle says。Can't see anything after chapter 3。

![2023-11-09_20-08](https://github.com/xinychen/latex-cookbook/assets/99662189/4c80390d-01a6-40a2-9b87-dd4a89263cc4)

**Comment by moyiun09** [comment]
@GEJXD 
![image](https://github.com/xinychen/latex-cookbook/assets/62366932/27b4f0e0-8df3-4ee8-b671-cbd8e6734d2b)

The author did not give a direct link here, but the content of the article exists. 
I think you can open the corresponding file directly.
https://nbviewer.org/github/xinychen/latex-cookbook/tree/main/
eg: version-1: chapter-3
https://nbviewer.org/github/xinychen/latex-cookbook/blob/main/version-1/chapter-3/section0.ipynb

@yxnchen 
Forgive my ignorance. If there is something wrong with what I said, please delete this message directly.
